all :sendmain1 sendmain2 recvmain1 recvmain2 recvmain3 recvmain4 recvmain5 recvmain6 recvmain7 

sendmain1: msg.cpp sendmain1.cpp
	g++ -o sendmain1 msg.cpp sendmain1.cpp

sendmain2: msg.cpp sendmain2.cpp
	g++ -o sendmain2 msg.cpp sendmain2.cpp

recvmain1: msg.cpp recvmain1.cpp
	g++ -o recvmain1 msg.cpp recvmain1.cpp

recvmain2: msg.cpp recvmain2.cpp
	g++ -o recvmain2 msg.cpp recvmain2.cpp

recvmain3: msg.cpp recvmain3.cpp
	g++ -o recvmain3 msg.cpp recvmain3.cpp

recvmain4: msg.cpp recvmain4.cpp
	g++ -o recvmain4 msg.cpp recvmain4.cpp

recvmain5: msg.cpp recvmain5.cpp
	g++ -o recvmain5 msg.cpp recvmain5.cpp

recvmain6: msg.cpp recvmain6.cpp
	g++ -o recvmain6 msg.cpp recvmain6.cpp

recvmain7: msg.cpp recvmain7.cpp
	g++ -o recvmain7 msg.cpp recvmain7.cpp

clean:
	rm -f sendmain1 sendmain2 recvmain1 recvmain2 recvmain3 recvmain4 recvmain5 recvmain6 recvmain7